### ISSUE TITLE
Newline invisibles should be subtle

### ISSUE THREAD

**Issue by athanclark** [james2doyle/atom-monokai-dark#10]
The ¬ symbol is used for newline characters when the invisibles are shown in Atom. However, in this theme (my favorite theme btw :) ), they are the same color as the main syntax.

You can fix this with the `.invisible-character` class:

```less
atom-text-editor, :host {
  // ...
  .invisible-character {
    color: // lightgoldenrodyellow
  }
}
```
